### ISSUE TITLE
add an action to retrieve the http and grpc urls

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/parca-k8s-operator#420]
### Enhancement Proposal

at the moment, parca publishes its (ingressed) http url in its status if active, but that has some downsides:
- the grpc entrypoint is not visible anywhere, and one needs to know that it's at port :7993.
- no easy way to get it programmatically, one would have to parse the juju status.

Proposal:
```
juju run parca/leader list-endpoints

result: 
  - ingressed_http_url: 0.0.0.0:7994
  - ingressed_grpc_url: 0.0.0.0:7993
  - direct_http_url: 0.0.0.0:7994
  - direct_grpc_url: 0.0.0.0:7993
```

prior art: https://github.com/canonical/tempo-coordinator-k8s-operator/blob/main/src/charm.py#L263

Question: do we want to include both ingressed and not-ingressed endpoints, or which one?
